name: teste_smartfit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  test: ^1.25.7
  bloc_test: ^10.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
